# https://github.com/jdblischak/smk-simple-slurm?tab=readme-ov-file
# https://bioconda.github.io/recipes/snakemake-executor-plugin-cluster-generic/README.html
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/`date +"%d-%m-%y"`/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%d-%m-%y"`/{rule}/{rule}-{wildcards}-%j.out
    --parsable

default-resources:
  - partition=regular
  - mem_mb=1000

restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
cluster-generic-cancel-cmd: scancel